[package]
name = "dyer"
version = "0.1.1-alpha"
authors = ["HomelyGuy"]
edition = "2018"
license = "MIT"
keywords = ["crawler", "spider", "web-crawling", "web-framework"]
categories = ["network-programming", "web-programming"]
description = " Dyer is designed for reliable, flexible and fast web-crawling, providing some high-level, comprehensive  features without compromising speed.  By means of event-driven, non-blocking I/O tokio and powerful, reliable [Rust programming"
homepage = "https://github.com/HomelyGuy"
repository = "https://github.com/HomelyGuy"
documentation = "https://docs.rs/dyer"
readme = "README"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde= {version="1.0", features=["derive"]}
serde_json='*'
tokio={ version = "0.2", features = [ "macros", "rt-threaded" ] }
futures="0.3"
typed-builder = "0.9"
#async-trait="0.1"
hyper = "0.13.8"
hyper-tls="0.4"
hyper-timeout="0.3"
brotli2='0.3'
flate2='1.0'
bytes="0.5.6"
signal-hook="0.1"
log="0.4"
rand="0.8"



