# modes that the software stay, possible value:
#    production 
#    development
mode = "development"

#in development, specify the debug level, possible value:
#    1 for error printing out 
#    2 for Task notified and Request notified, extrated Item summary more with 1
#    3 for Task summary, Request summary, Item summary Profile notified, more with 2
#    4 for Task Request Item details and Profile summary more with 3
#    5 for Task, Request, Result, Profile details more with 4

#specify the output Profile directory
path_profile = "data/profile"

#specify the output Task directory
path_task = "data/task"

#specify the output Request directory
path_request = "data/request"

#specify the output Result directory
path_result = "data/result"

#start new session and direct to start_request
skip_history = false

# LOG CONFIGURATION #FIXME to merge log4rs config with this file








